version: '3.8'

services:
  yt-dlp-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Flask app
      - "8081:8081"  # WebSocket server
    volumes:
      - ./downloads:/app/downloads
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
